version: "3"
services:
  web:
    image: nclcloudcomputing/javabenchmarkapp:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  db:
    image: mongo
networks:
  webnet:
